ALTER TABLE mktPlace.cars
    ADD COLUMN storage INTEGER DEFAULT 0,
    ALTER COLUMN createDate TYPE TIMESTAMPTZ,
    ALTER COLUMN updateDate TYPE TIMESTAMPTZ;

ALTER TABLE mktPlace.bikes
    ADD COLUMN storage INTEGER DEFAULT 0,
    ALTER COLUMN createDate TYPE TIMESTAMPTZ,
    ALTER COLUMN updateDate TYPE TIMESTAMPTZ;

ALTER TABLE mktPlace.boats
    ADD COLUMN storage INTEGER DEFAULT 0,
    ALTER COLUMN createDate TYPE TIMESTAMPTZ,
    ALTER COLUMN updateDate TYPE TIMESTAMPTZ;

ALTER TABLE mktPlace.planes
    ADD COLUMN storage INTEGER DEFAULT 0,
    ALTER COLUMN createDate TYPE TIMESTAMPTZ,
    ALTER COLUMN updateDate TYPE TIMESTAMPTZ;
