ALTER TABLE mktplace.bikes
ADD COLUMN rentalPriceMonthly MONEY;
ADD COLUMN stripeProductId VARCHAR(75) UNIQUE NOT NULL;
ADD COLUMN stripePriceId VARCHAR(75) UNIQUE NOT NULL;

ALTER TABLE mktplace.boats
ADD COLUMN rentalPriceMonthly MONEY;
ADD COLUMN stripeProductId VARCHAR(75) UNIQUE NOT NULL;
ADD COLUMN stripePriceId VARCHAR(75) UNIQUE NOT NULL;

ALTER TABLE mktplace.cars
ADD COLUMN rentalPriceMonthly MONEY;
ADD COLUMN stripeProductId VARCHAR(75) UNIQUE NOT NULL;
ADD COLUMN stripePriceId VARCHAR(75) UNIQUE NOT NULL;

ALTER TABLE mktplace.planes
ADD COLUMN rentalPriceMonthly MONEY;
ADD COLUMN stripeProductId VARCHAR(75) UNIQUE NOT NULL;
ADD COLUMN stripePriceId VARCHAR(75) UNIQUE NOT NULL;